services:

  app:
  build: .
  contariner_name : bob_app
  ports:
    - "8000:8000"
  depends_on:
    - mysql
    - redis
  environment:
    DB_HOST: mysql # 컨테이너 이름  X, 서비스 명으로 접근
    DB_PORT: 3306 # 내부 포트 사용
    DB_USER: bob_user
    DB_PASSWORD: bobpass
    DB_NAME: bob_movie_db
    REDIS_HOST: redis

  volumes:
    - .:/app # 개발 시 코드 변경 실시간 반영
  mysql:
    image: mysql:8.0
    container_name: bob_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: bob_movie_db
      MYSQL_USER: bob_user
      MYSQL_PASSWORD: bobpass
    ports:
      - "13306:3306" 
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: bob_redis
    ports:
      - "6379:6379"

volumes:
  mysql_data:

# 기존 컨테이너 정리
# docker-compose down

# 다시 실행
# docker-compose up -d

# 연결 테스트 (포트 3307로)
# docker exec -it bob_mysql mysql -u bob_user -pbobpass bob_movie_db -e "SELECT 1;"

# 또는 로컬에서
# mysql -h 127.0.0.1 -P 3307 -u bob_user -pbobpass bob_movie_db