"""add user_ratings table

Revision ID: 13eeb811d049
Revises: 
Create Date: 2026-01-23 15:01:22.030209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '13eeb811d049'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_ratings', 'rating',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.drop_index('unique_user_movie', table_name='user_ratings')
    op.create_unique_constraint('unique_user_movie_rating', 'user_ratings', ['user_id', 'movie_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_movie_rating', 'user_ratings', type_='unique')
    op.create_index('unique_user_movie', 'user_ratings', ['user_id', 'movie_id'], unique=True)
    op.alter_column('user_ratings', 'rating',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
