"""add movie_stats table

Revision ID: cd41a7849b57
Revises: 13eeb811d049
Create Date: 2026-03-23 15:09:16.323738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cd41a7849b57'
down_revision: Union[str, None] = '13eeb811d049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_stats',
    sa.Column('movie_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('avg_rating', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('movie_id')
    )
    op.alter_column('user_ratings', 'rating',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.drop_index('unique_user_movie', table_name='user_ratings')
    op.create_unique_constraint('unique_user_movie_rating', 'user_ratings', ['user_id', 'movie_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_movie_rating', 'user_ratings', type_='unique')
    op.create_index('unique_user_movie', 'user_ratings', ['user_id', 'movie_id'], unique=True)
    op.alter_column('user_ratings', 'rating',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.drop_table('movie_stats')
    # ### end Alembic commands ###
